version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: "/docs"
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    groups:
      docs-python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - "*"